### ISSUE TITLE
I open a song and the song starts playing... then I add another song to the lineup and the first song I open stops on its own and doesn't play until I use the skip command

### ISSUE THREAD

**Issue by ghost** [FirezTheGreat/Celestial#2]
I open a song and the song starts playing... then I add another song to the lineup and the first song I open stops on its own and doesn't play until I use the skip command

**Comment by FirezTheGreat** [comment]
let me check

**Comment by FirezTheGreat** [comment]
[fixed](https://github.com/FirezTheGreat/Celestial/commit/3235008ff103c47c86b6cc4a6eb1ac445c3b319f)
